spring:
    datasource:
        url: jdbc:mysql://localhost:3306/game_reco
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        platform: mysql
        initialize: false
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            database-platform: org.hibernate.dialect.MySQL5Dialect

---

spring:
    profiles: container
    datasource:
        url: jdbc:mysql://mysql:3306/game_reco
        username: dbuser
        password: dbpwd
        initialize: true